<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EventLoom.AspNetCore" Version="EventLoomPackageVersion" />
    <PackageReference Include="EventLoom.Analyzers" Version="EventLoomPackageVersion" PrivateAssets="all" />
    <PackageReference Include="EventLoom.EntityFrameworkCore.Sqlite" Version="EventLoomPackageVersion" />
  </ItemGroup>
</Project>
